### ISSUE TITLE
US 1 “Footer Nav”

### ISSUE THREAD

**Issue by TuncAlt** [TuncAlt/capstone-project#1]
## Value Proposition

As a user, 
I want a Footer Nav on the website, 
so that I can easily access the Home page, Add Device Form and Search function from any page on the website.
​

## Description

​
<img width="295" alt="Screenshot 2023-03-03 at 15 16 14" src="https://user-images.githubusercontent.com/64401926/222743500-eea72d2a-a517-4278-9d8b-6cadaf40cfeb.png">

## Acceptance Criteria

- [ ] - The Footer Nav should be present on all pages of the website.
- [ ] - The Home link (Home Icon) should take me to the homepage of the website.
- [ ] - The Add Device Form link (+ Icon) should take me to a form where I can add a new device to the website.
- [ ] - The Search (Search glas?) function link should take me to a search bar where I can search for devices on the website.​

## Tasks

- [ ]  Create and design the Footer Nav
- [ ]  Add the Footer Nav to all pages/index.js?
- [ ]  Implement the Home link functionality
- [ ]  Implement the Add Device Form link functionality
- [ ]  Implement the Search function link functionality
      ​

## Complexity

... (S)

**Comment by SarahWett** [comment]
Looks Good!
