### ISSUE TITLE
User Story 6: DevicePage

### ISSUE THREAD

**Issue by TuncAlt** [TuncAlt/capstone-project#13]
# User Story 6: DevicePage

## Value Proposition

As a user, I want to be able to view the selected device on a DevicePage. 

So I can See the temperature history data as a table.

## Description

The DevicePage feature allows users to easily monitor the status of their selected device, view temperature history data as a chart and table.

![Image](https://user-images.githubusercontent.com/64401926/225322004-3b406cfe-4602-4365-86d3-5004cf21c614.png)

## Acceptance Criteria

To consider the User Story 6: DevicePage complete, the following criteria must be met:

- [x]  The DevicePage should display the name of the selected device.
- [x]  The DevicePage should display the current temperature reading of the selected device.
- [x]  The DevicePage should include a history table showing the last 5 temperature readings of the selected device.
- [x]  All temperature readings should be displayed in Celsius.
- [x]  The DevicePage should have a clean and intuitive user interface.

## Tasks
- [x]  Create a layout for the DevicePage
- [x]  Display the name of the selected device
- [x]  Display the current temperature reading of the selected device
- [x]  Create a history table showing the last 5 temperature readings of the selected device
- [x]  Ensure all temperature readings are displayed in Celsius

**Comment by MartinK1983** [comment]
Nice app. Cool Styling.

**Comment by TuncAlt** [comment]
updated UserStory
