### ISSUE TITLE
User Story 7 Temperature Edit Page

### ISSUE THREAD

**Issue by TuncAlt** [TuncAlt/capstone-project#15]
## User Story 7 Temperature Edit Page

As a user, 

I want to edit, search, and delete the temperature readings that have been logged for a specific device on the EditPage. 

So I can keep track of the temperature readings and make changes as necessary. 

## Description

![Screenshot 2023-03-15 at 16 47 33](https://user-images.githubusercontent.com/64401926/225365047-795c832d-2720-42ce-9017-6b291f3e790d.png)

## Acceptance Criteria

- [x]  The EditPage should be accessible and easy to navigate to from the devicePage.
- [x] The EditPage should display the name of the selected device and a list of its temperature readings.
- [x] The EditPage should have a search bar that allows the user to search for specific temperature readings by date or temperature.
- [x]  The EditPage should allow the user to edit or delete existing temperature readings.
- [x]  The EditPage should have a confirmation prompt before deleting a temperature reading.
- [x] The EditPage should have a button to add a new temperature reading for the selected device.
- [x] The EditPage should have proper styling and be user-friendly.

## Tasks

- [x]  Add a button or link to navigate to the EditPage from the main page
- [x]  Display the name of the selected device on the EditPage
- [x]  Display a list of temperature readings for the selected device
- [x]  Add a search bar to the EditPage that allows the user to search for specific temperature readings by date or temperature
- [x]  Add functionality to edit existing temperature readings on the EditPage
- [x]  Add functionality to delete existing temperature readings on the EditPage with a confirmation prompt
- [x]  Add a button to add a new temperature reading for the selected device on the EditPage
- [x]  Add proper styling to the EditPage to make it user-friendly
