### ISSUE TITLE
US8 DeviceEditPage

### ISSUE THREAD

**Issue by TuncAlt** [TuncAlt/capstone-project#17]
## Value Proposition 

As a user, 
I want to be able to edit and delete the specs of a device on the EditPage, 
so that I can keep the device information up-to-date and accurate.

## Description

<img width="209" alt="Screenshot 2023-03-21 at 08 23 01" src="https://user-images.githubusercontent.com/64401926/226540866-53d120fe-ee9a-4388-b060-e234b2592134.png">

## Acceptance Criteria

- The EditPage should be accessible and easy to navigate from the device page.
- The EditPage should display the name of the selected device and its current specs.
- The EditPage should allow the user to edit the specs of the selected device.
- The EditPage should have a confirmation prompt before deleting the device.
- The EditPage should have proper styling and be user-friendly.

## Tasks

- [x]  Add a button or link to navigate to the EditPage from the device page
- [x]  Display the name of the selected device and its current specs on the EditPage
- [x]  Add functionality to edit the specs of the selected device on the EditPage
- [x]  Add functionality to delete the selected device on the EditPage with a confirmation prompt
- [x]  Add proper styling to the EditPage to make it user-friendly

**Comment by Manu7864z** [comment]
LGTM!
