### ISSUE TITLE
US9-LineChart

### ISSUE THREAD

**Issue by TuncAlt** [TuncAlt/capstone-project#19]
## Value Proposition

As a User  
I want a line Chart
so that the last 5 readings get monitored on the device page.
​

## Description

Line Chart -> which show last 5 temperature readings
​

## Acceptance Criteria

- [ ] last 5 readings gets sorted,
- [ ] line chart gets data from readings and gets displayed on device page,
- [ ] the line chart should have no labels,
- [ ] the design is minimalistic
      ​

## Tasks

- [ ] install chart.js for react
- [ ] get readings
- [ ] slice the readings array into 5
- [ ] display the readings on device Page
      ​

## Complexity

... (L)
