### ISSUE TITLE
US 2 "Add new Device Form"

### ISSUE THREAD

**Issue by TuncAlt** [TuncAlt/capstone-project#2]
## Value Proposition

As a user who manages multiple cooling devices, 

I want to be able to add new devices to the app, 

so that I can track their temperature readings and monitor their status alongside my existing devices.
​

## Description
<img width="290" alt="Screenshot 2023-03-03 at 15 30 01" src="https://user-images.githubusercontent.com/64401926/222746797-3823c075-3f6e-4418-973c-b67a130153b1.png">

## Acceptance Criteria

- [ ]  The app provides a simple and intuitive form for adding new devices.
- [ ] When adding a new device, I can enter its name, location, Type, choose whether the data is generated automatically or manually (toggle button).
- [ ] I can specify the device's minimum and maximum temperature thresholds to help me monitor its status.
- [ ] Once added, the new device is stored in the local storage.
- [ ] The app provides clear feedback when a new device is successfully added or if there are any issues during the process.
- [ ] The device information can be easily edited or deleted if needed.
      ​

## Tasks

- [ ]  Design the user interface for adding a new device, making sure it is simple, intuitive, and easy to use.
- [ ]  Create the Add New Device Form
- [ ]  Implement the storage functionality to store the new device information in the database.
- [ ]  Implement the data-generating functionality (on/off toggle Button)
- [ ]  Implement validation checks to ensure that the user enters all necessary information and that it is in the correct format.
- [ ]  Write unit tests to ensure that the new device is added correctly and that the app provides clear feedback in case of errors.
      ​

## Complexity

... (XL)
