### ISSUE TITLE
US 10 Back Button 

### ISSUE THREAD

**Issue by TuncAlt** [TuncAlt/capstone-project#22]
## Value Proposition

**As a User
**I want to have a back button on the temperature Readings Page
**so that i am able to go back to the device page. 
​

## Description

Backbutton on the temperature Reading page, which navigates back to the device Page.
​

## Acceptance Criteria

- [ ] button navigates you back to the device page
- [ ] well designed 
      ​

## Tasks

- [ ] add a button to the temperature reading 
- [ ] on click router.back​

## Complexity

S
