### ISSUE TITLE
US 3 "Form Header Navigation"

### ISSUE THREAD

**Issue by TuncAlt** [TuncAlt/capstone-project#3]
## Value Proposition

As a user, 
I want to easily navigate between the "Add Device" and "Log Temp" forms,
so that I can quickly add new devices and log temperatures for them.

## Description

![Screenshot 2023-03-02 at 12 37 00](https://user-images.githubusercontent.com/64401926/222754681-ed69f521-2846-456e-ac73-61e4e38c667a.png)​

## Acceptance Criteria

- [ ] The navigation header should be present on the "Add Device" and "Log Temp" forms.
- [ ] The navigation header should include links to both forms.
- [ ] The navigation header should clearly indicate which page is currently active.
- [ ] The navigation header should be responsive and work well on both desktop and mobile devices.
- [ ] Clicking on the link in the navigation header should take the user directly to the corresponding form.
      ​

## Tasks

- [ ]  Add navigation header to "Add Device" form
- [ ]  Include links to both forms in the navigation header
- [ ]  Clearly indicate which page is currently active in the navigation header
- [ ]  Ensure the navigation header is responsive and works well on both desktop and mobile devices
- [ ]  Test clicking on the links in the navigation header to verify they take the user directly to the corresponding form
      ​

## Complexity

... (M)
