### ISSUE TITLE
US 4 "Log Temperature Form"

### ISSUE THREAD

**Issue by TuncAlt** [TuncAlt/capstone-project#4]
## Value Proposition

As a user, 
I want to be able to log new temperature records, select the device used, 
and select the date.
So that the temperature is logged for selected device.

## Description
<img width="290" alt="Screenshot 2023-03-03 at 16 09 10" src="https://user-images.githubusercontent.com/64401926/222755954-4badfc71-2973-408f-b4aa-2acda44b88f6.png">

## Acceptance Criteria

- [ ] The form should include fields for temperature, device, and notes.
- [ ] The Form Header Navigation should be displayed 
- [ ] The temperature field should only accept numerical values in Fahrenheit or Celsius.
- [ ] The device field should allow the user to select from a list of pre-defined options.
- [ ] Upon submission, the form should save the data to a database for future reference.
- [ ] Error Handling if invalid values are typed in.
      ​

## Tasks

- [ ]  Create form with input fields for temperature, device, and notes
- [ ]  Implement validation for temperature field to only accept numerical values in Celsius
- [ ]  Implement device field as a dropdown list with pre-defined options from the database to select device
- [ ]  Implement submission functionality to save data to a database
- [ ]  Implement error handling for invalid temperature values
- [ ]  Ensure the form is easy to use and visually appealing, with clear labels and instructions​

## Complexity

... (M)

**Comment by Manu7864z** [comment]
Nice design prototype. :D
